In [ ]:
# Assign 4
# Dataset  gender prediction

In [1]:
# Imports
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split


from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.linear_model import LogisticRegression








#import ML evaluation metrics
from sklearn.metrics import accuracy_score, f1_score,recall_score,precision_score
from sklearn.model_selection import ShuffleSplit, cross_val_predict, cross_val_score, LeavePOut
from sklearn.model_selection import train_test_split
from sklearn import metrics, model_selection



In [2]:
# Read Dataset
df = pd.read_csv('gender_prediction.csv')
df


height  weight beard hair_length  shoe_size scarf eye_color  gender
0       71     176   yes       short         44    no     black    male
1       68     165    no        bald         41    no     black    male
2       62     132    no      medium         37   yes      blue  female
3       65     138    no        long         38    no      gray  female
4       70     197   yes      medium         43    no      gray    male
..     ...     ...   ...         ...        ...   ...       ...     ...
75      65      99    no       short         39   yes     green  female
76      61      98    no       short         37    no     brown  female
77      67     119   yes       short         40    no     black    male
78      70     190   yes      medium         43    no      gray    male
79      62     142   yes        long         37    no      blue  female

[80 rows x 8 columns]

In [3]:
malecount = df[df['gender']=='male'].count()
femalecount = df[df['gender']=='female'].count()


In [4]:
ratio = malecount/femalecount

In [5]:
# check categorical data 
a =df.select_dtypes(include=['object']).columns.tolist()


# Q2# Apply Random Forest, Support Vector Machines, and Multilayer Perceptron classification algorithms


In [6]:
# dataprepration  for  algos

height = df['height']
weight = df['weight']
beard = df['beard']
hair_length = df['hair_length']
shoe_size = df['shoe_size']
scarf = df['scarf']
eye_color = df['eye_color']
gender=df['gender']


In [7]:
#Categorical data conversion into numeric form
labels = preprocessing.LabelEncoder()
beard_encod = labels.fit_transform(beard)
hairlength_encod = labels.fit_transform(hair_length)
scarf_encod = labels.fit_transform(scarf)
eyecolor_encod = labels.fit_transform(eye_color)
gender_encod = labels.fit_transform(gender)


In [8]:
#combining input

input_ = list(zip(height,weight,beard_encod,hairlength_encod,shoe_size,scarf_encod,eyecolor_encod))



In [9]:
#output 
output = gender_encod

In [10]:
# Standard Value split = 66% train  33%test
X_train, X_test, Y_train, Y_test = train_test_split(input_, output, test_size = 0.33, random_state = 9)

In [11]:
#Applying Random Forest, Support Vector Machines, and Multilayer Perceptron 




In [12]:
#Applying Random Forest

model = RandomForestClassifier()

# Training and Testing on random forest
model.fit(X_train,Y_train)
Test_ = model.predict(X_test)

#Accuracy of on test data
accuracy = accuracy_score(Y_test, Test_)*100
print("Accuracy using Random Forest is = ")
print(accuracy)

#Confusion matrix
cm = metrics.confusion_matrix(Y_test,Test_)
print("Confusion Matrix using Random Forest is \n" )
print(cm)

#  report
Class_report = metrics.classification_report(Y_test, Test_)
print ('Classification report \n')
print(Class_report)

Accuracy using Random Forest is = 
96.29629629629629
Confusion Matrix using Random Forest is 

[[12  1]
 [ 0 14]]
Classification report 

              precision    recall  f1-score   support

           0       1.00      0.92      0.96        13
           1       0.93      1.00      0.97        14

    accuracy                           0.96        27
   macro avg       0.97      0.96      0.96        27
weighted avg       0.97      0.96      0.96        27



In [13]:
#Applying Support Vector Machines

model = SVC()

# Training and Testing on  Support Vector Machines
model.fit(X_train,Y_train)
Test_ = model.predict(X_test)

#Accuracy of on test data
accuracy = accuracy_score(Y_test, Test_)*100
print("Accuracy using Random Forest is = ")
print(accuracy)

#Confusion matrix
cm = metrics.confusion_matrix(Y_test,Test_)
print("Confusion Matrix using Random Forest is \n" )
print(cm)

#  report
Class_report = metrics.classification_report(Y_test, Test_)
print ('Classification report \n)
print(Class_report)

SyntaxError: EOL while scanning string literal (Temp/ipykernel_19176/1823591108.py, line 21)

In [14]:
#Applying Multilayer Perceptron


model = MLPClassifier()
# Training and Testing on Multilayer Perceptron
model.fit(X_train,Y_train)
Test_ = model.predict(X_test)

#Accuracy of on test data
accuracy = accuracy_score(Y_test, Test_)*100
print("Accuracy using Random Forest is = ")
print(accuracy)

#Confusion matrix
cm = metrics.confusion_matrix(Y_test,Test_)
print("Confusion Matrix using Random Forest is \n" )
print(cm)

#  report
Class_report = metrics.classification_report(Y_test, Test_)
print ('Classification report \n')
print(Class_report)

Accuracy using Random Forest is = 
85.18518518518519
Confusion Matrix using Random Forest is 

[[10  3]
 [ 1 13]]
Classification report 

              precision    recall  f1-score   support

           0       0.91      0.77      0.83        13
           1       0.81      0.93      0.87        14

    accuracy                           0.85        27
   macro avg       0.86      0.85      0.85        27
weighted avg       0.86      0.85      0.85        27



C:\Users\Super\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


##### using 80/20 train test on the given dataset


In [15]:
# 80/20 train test
X_train, X_test, Y_train, Y_test = train_test_split(input_, output, test_size = 0.2, random_state = 9)


In [16]:
#Applying Random Forest

model = RandomForestClassifier()

# Training and Testing on random forest
model.fit(X_train,Y_train)
Test_ = model.predict(X_test)

#Accuracy of on test data
accuracy = accuracy_score(Y_test, Test_)*100
print("Accuracy using Random Forest is = ")
print(accuracy)

#Confusion matrix
cm = metrics.confusion_matrix(Y_test,Test_)
print("Confusion Matrix using Random Forest is \n" )
print(cm)

#  report
Class_report = metrics.classification_report(Y_test, Test_)
print ('Classification report \n')
print(Class_report)

Accuracy using Random Forest is = 
93.75
Confusion Matrix using Random Forest is 

[[7 1]
 [0 8]]
Classification report 

              precision    recall  f1-score   support

           0       1.00      0.88      0.93         8
           1       0.89      1.00      0.94         8

    accuracy                           0.94        16
   macro avg       0.94      0.94      0.94        16
weighted avg       0.94      0.94      0.94        16



In [17]:
#Applying Support Vector Machines

model = SVC()

# Training and Testing on Support Vector Machines
model.fit(X_train,Y_train)
Test_ = model.predict(X_test)

#Accuracy of on test data
accuracy = accuracy_score(Y_test, Test_)*100
print("Accuracy using Random Forest is = ")
print(accuracy)

#Confusion matrix
cm = metrics.confusion_matrix(Y_test,Test_)
print("Confusion Matrix using Random Forest is \n" )
print(cm)

#  report
Class_report = metrics.classification_report(Y_test, Test_)
print ('Classification report \n')
print(Class_report)

Accuracy using Random Forest is = 
75.0
Confusion Matrix using Random Forest is 

[[5 3]
 [1 7]]
Classification report 

              precision    recall  f1-score   support

           0       0.83      0.62      0.71         8
           1       0.70      0.88      0.78         8

    accuracy                           0.75        16
   macro avg       0.77      0.75      0.75        16
weighted avg       0.77      0.75      0.75        16



In [18]:
#Applying Multilayer Perceptron

model = MLPClassifier()
# Training and Testing on Multilayer Perceptron
model.fit(X_train,Y_train)
Test_ = model.predict(X_test)

#Accuracy of on test data
accuracy = accuracy_score(Y_test, Test_)*100
print("Accuracy using Random Forest is = ")
print(accuracy)

#Confusion matrix
cm = metrics.confusion_matrix(Y_test,Test_)
print("Confusion Matrix using Random Forest is \n" )
print(cm)

#  report
Class_report = metrics.classification_report(Y_test, Test_)
print ('Classification report \n')
print(Class_report)

Accuracy using Random Forest is = 
50.0
Confusion Matrix using Random Forest is 

[[0 8]
 [0 8]]
Classification report 

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       0.50      1.00      0.67         8

    accuracy                           0.50        16
   macro avg       0.25      0.50      0.33        16
weighted avg       0.25      0.50      0.33        16



C:\Users\Super\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Super\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Super\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


##### powerful attributes removal   and results


##### Attr removed = hair lenght and scarf


In [20]:
#combining input after removal of attributes

input_Updated = list(zip(height,weight,hairlength_encod,shoe_size,eyecolor_encod))

In [21]:
#output 
output = gender_encod

In [22]:
# 80/20 train test
X_train_u, X_test_u, Y_train_u, Y_test_u = train_test_split(input_Updated, output, test_size = 0.2, random_state = 9)


In [23]:
#Applying Random Forest

model = RandomForestClassifier()

# Training and Testing on random forest
model.fit(X_train_u,Y_train_u)
Test_ = model.predict(X_test_u)

#Accuracy of on test data
accuracy = accuracy_score(Y_test_u, Test_)*100
print("Accuracy using Random Forest is = ")
print(accuracy)

#Confusion matrix
cm = metrics.confusion_matrix(Y_test_u,Test_)
print("Confusion Matrix using Random Forest is \n" )
print(cm)

#  report
Class_report = metrics.classification_report(Y_test_u, Test_)
print ('Classification report \n')
print(Class_report)

Accuracy using Random Forest is = 
93.75
Confusion Matrix using Random Forest is 

[[7 1]
 [0 8]]
Classification report 

              precision    recall  f1-score   support

           0       1.00      0.88      0.93         8
           1       0.89      1.00      0.94         8

    accuracy                           0.94        16
   macro avg       0.94      0.94      0.94        16
weighted avg       0.94      0.94      0.94        16



In [24]:
#Applying Support Vector Machines

model = SVC()

# Training and Testing on random forest
model.fit(X_train_u,Y_train_u)
Test_ = model.predict(X_test_u)

#Accuracy of on test data
accuracy = accuracy_score(Y_test_u, Test_)*100
print("Accuracy using Random Forest is = ")
print(accuracy)

#Confusion matrix
cm = metrics.confusion_matrix(Y_test_u,Test_)
print("Confusion Matrix using Random Forest is \n" )
print(cm)

#  report
Class_report = metrics.classification_report(Y_test_u, Test_)
print ('Classification report \n')
print(Class_report)

Accuracy using Random Forest is = 
75.0
Confusion Matrix using Random Forest is 

[[5 3]
 [1 7]]
Classification report 

              precision    recall  f1-score   support

           0       0.83      0.62      0.71         8
           1       0.70      0.88      0.78         8

    accuracy                           0.75        16
   macro avg       0.77      0.75      0.75        16
weighted avg       0.77      0.75      0.75        16



In [25]:
#Applying Multilayer Perceptron

model = MLPClassifier()

# Training and Testing on  Multilayer Perceptron
model.fit(X_train_u,Y_train_u)
Test_ = model.predict(X_test_u)

#Accuracy of on test data
accuracy = accuracy_score(Y_test_u, Test_)*100
print("Accuracy using Random Forest is = ")
print(accuracy)

#Confusion matrix
cm = metrics.confusion_matrix(Y_test_u,Test_)
print("Confusion Matrix using Random Forest is \n" )
print(cm)

#  report
Class_report = metrics.classification_report(Y_test_u, Test_)
print ('Classification report \n')
print(Class_report)

Accuracy using Random Forest is = 
68.75
Confusion Matrix using Random Forest is 

[[4 4]
 [1 7]]
Classification report 

              precision    recall  f1-score   support

           0       0.80      0.50      0.62         8
           1       0.64      0.88      0.74         8

    accuracy                           0.69        16
   macro avg       0.72      0.69      0.68        16
weighted avg       0.72      0.69      0.68        16



##### Q3 apply  DTC with MC cross validation and LPOut cross validation


In [26]:
# Decision Model tree Implementation
model = DecisionTreeClassifier()

In [27]:
#Monte Carlo
splitcv=ShuffleSplit(n_splits=12,test_size=0.33,random_state=9)
f1 = cross_val_score(model, input_Updated, output,scoring='f1', cv=splitcv).mean()
print('f1 score using monte carlo')
print(f1)

f1 score using monte carlo
0.9497986496332972


In [ ]:
#LeavePout cross validation
l_p_out = LeavePOut(p=5)
f1 = cross_val_score(model, input_Updated, output,scoring='f1', cv=l_p_out).mean()
print('f1 score using l_p_out')
print(f1)

##### Q4


In [ ]:
# Read Dataset
df = pd.read_csv('gender_prediction.csv')



# dataprepration  for  algos


input_ = df.drop('gender', axis=1)
output=df['gender']

#Categorical data conversion into numeric form
labels = preprocessing.LabelEncoder()
input_.beard_encod = labels.fit_transform(input_.beard)
input_hairlength_encod = labels.fit_transform(input_.hair_length)
input_scarf_encod = labels.fit_transform(input_.scarf)
input_eyecolor_encod = labels.fit_transform(input_.eye_color)
output_gender_encod = labels.fit_transform(output.gender)

In [ ]:
# Sepration of train and test instances


#train and test instances
train_input = input_.iloc[:82]
train_output = output.iloc[:82]
test_input = input_.iloc[82:]
test_output = output.iloc[82:]


In [ ]:
# implementing GNB
model_GNB = GaussianNB()
model_GNB.fit(train_input,train_output)

predictions = model_GNB.predict(test_up)


accuracy = accuracy_score(test_input, predictions)*100
print("Accuracy")
print(accuracy)

recall = recall_score(test_output,predictions)
print("Recall = ")
print(recall)


precision = precision_score(test_output,predictions)
print("Precision")
print(precision)
